build:
  - image: node
    command: ["node", "--version"]
  - image: node
    command: ["npm", "--version"]
  - image: node:10.15.0
    command: ["node", "--version"]
  - image: node:10.15.0
    command: ["npm", "--version"]
  - image: alpine
    command: ["apk", "update"]